---
- name: start nim
  shell: '/opt/nimsoft/bin/niminit start'
  become: true
  become_user: root
  args:
    executable: /bin/bash

- name: stop nim
  shell: '/opt/nimsoft/bin/niminit stop'
  become: true
  become_user: root
  args:
    executable: /bin/bash

